name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: docker://goharbor/registry:latest
        with:
          args: |
            hugo --minify

      - name: Build the site
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -w /src klakegg/hugo:latest hugo -D

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'  # Mengupload folder public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
