name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti dengan branch utama Anda jika berbeda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: jakejarvis/hugo-actions@v0.1.0
        with:
          hugo_version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
